packages:
  - packages/*

catalog:
  pinia: 3.0.4

catalogs:
  test:
    '@pinia/testing': 1.0.3
    '@vue/test-utils': 2.5.0
    happy-dom: 20.14.0
    vitest: 4.1.11
  tool:
    '@vitejs/plugin-vue': 6.0.8
    '@vue/compiler-dom': 3.5.42
    '@vue/server-renderer': 3.5.42
    vite: 7.3.6

onlyBuiltDependencies:
  - esbuild

packageExtensions:
  # TODO: Uncomment to fix issue
  #'@pinia/testing':
  #  peerDependencies:
  #    vue: ^3.5.13

  # HACK: No peerDependencies defined in upstream latest package (fixed in main branch)
  '@vue/test-utils@2.4.6':
    peerDependencies:
      '@vue/compiler-dom': ^3.5.13
      '@vue/server-renderer': ^3.5.13
      vue: ^3.5.13
