packages:
  - packages/*

catalog:
  pinia: 3.0.4

catalogs:
  test:
    '@pinia/testing': 1.0.2
    '@vue/test-utils': 2.4.6
    happy-dom: 20.6.1
    vitest: 4.0.18
  tool:
    '@vitejs/plugin-vue': 6.0.4
    '@vue/compiler-dom': 3.5.13
    '@vue/server-renderer': 3.5.13
    vite: 7.3.1

onlyBuiltDependencies:
  - esbuild

packageExtensions:
  # TODO: Uncomment to fix issue
  #'@pinia/testing':
  #  peerDependencies:
  #    vue: ^3.5.13

  # HACK: No peerDependencies defined in upstream latest package (fixed in main branch)
  '@vue/test-utils@2.4.6':
    peerDependencies:
      '@vue/compiler-dom': ^3.5.13
      '@vue/server-renderer': ^3.5.13
      vue: ^3.5.13
